### ISSUE TITLE
Punctuation, new line and carriage return characters should be ignored

### ISSUE THREAD

**Issue by thebuddhaswords** [thebuddhaswords/BW2#1]
Currently, Pali words with punctuation or non-alphabetical characters following them are not recognised by the Pali Lookup. For example , if a Pali word is followed by a carriage return (\r) or new line (\n) the word is not recognised. Similarly the "ti construction causes the preceding word to also not be recognised.  

Pali words with inital capitalisation are handled correctly.

**Comment by bdhrs** [comment]
I've fixed the case where "ti is not being recognised. Please note any others examples here of actual words not being found. It could be punctuation, it could be something else.

**Comment by cittadhammo** [comment]
Can you give an example @thebuddhaswords ?

**Comment by thebuddhaswords** [comment]
Venerable, the two character fix you made to the Pali Lookup script has addressed the issue where there are carriage returns and new lines within a Pali paragraph. It has been tested and uploaded to the live web site. Nice work! Closing this issue.
