### ISSUE TITLE
Pali words with no match in dictionary - pop-up is empty  

### ISSUE THREAD

**Issue by thebuddhaswords** [thebuddhaswords/BW2#2]
If a Pali word is not found in the dictionary, the pop-up consists of a single line (the empty pop-up box)

I'll create an issue to locate any Pali words that are in BW but not the DPD. This should unearth typos and stray &shy; characters etc. but perhaps it would be tidier if the pop-up box was hidden if there is no matching dictionary entry? Thoughts? 

![image](https://github.com/thebuddhaswords/BW2/assets/96769121/fe63833a-d2e7-498d-b83c-d5ab1f417b72)

**Comment by cittadhammo** [comment]
> In the rare cases where there is no match, perhaps there could be a ? so that the popup box doesn't collapse? What do you think? Maybe hide the box completely if there's no match??

**Comment by cittadhammo** [comment]
> In instances where someone (probably me or a rogue regex) has put carriage return and new lines in the middle of Pali paragraphs, it breaks the Lookup. See   https://thebuddhaswords.net/mn/mn8x.html for an example of this. It may not occur anywhere else but I can't find other instances so probably best to programmatically ignore regex \r and regex \n

**Comment by thebuddhaswords** [comment]
I've looked for instances where there is no match and they are very rare. If there is a word with n instead of ṅ there is no match but I'll raise that as a separate issue and close this one.
