### ISSUE TITLE
Identify Pali words in DPD but not in BW

### ISSUE THREAD

**Issue by thebuddhaswords** [thebuddhaswords/BW2#3]
Venerable Bodhirasa may have the tools to identify Pali words that are in BW but not in DPD. I've found some examples where there were stray &shy; entries and there are probable others that will come to light with such a comparison. I'll email him to see if he is able to help.

**Comment by bdhrs** [comment]
I've added my latest data, so there should be very few missing words now. The only two caes that comes to mind are spelling mistakes and variant readings, which I will add to the data when i get  a chance. 

Please keep a list here of missing any words

**Comment by thebuddhaswords** [comment]
Where there is a carriage return and line break inside a Pali paragraph, it breaks the Pali Lookup e.g. **anekapariyāyena(carriage return, new line - regex \r\n) dhammo pakāsito** 
![image](https://github.com/thebuddhaswords/BW2/assets/96769121/dcb6e901-425d-4137-99e9-e80acebb50eb)
Constructions such as bhikkhave"ti , saddhamman"ti , dhāressantī"ti etc. do not show the definition of the Pali word before the end quote "ti"
![image](https://github.com/thebuddhaswords/BW2/assets/96769121/942780f5-3470-4891-b2e4-45680b14d19a)

**Comment by bdhrs** [comment]
Can you psl post a link to the sutta with "anekapariyāyena(carriage return, new line - regex \r\n) dhammo pakāsito" i'm struggling to find an example. 

In the second example that is the standard behaviour in DPD as well, otherwise if it recurses and starts looking up again, the results start getting hit and miss. At that point it's up to the user to click on a word to get the meaning they want. 
![image](https://github.com/thebuddhaswords/BW2/assets/64521731/184f289b-0143-4c5d-bc6d-513954492964)

So i suggest to make that a new issue, that words in the pop-up are clickable, or suggest another solution. Ven. Cittadhammo had mentioned the idea of a dictionary bar / footer that could have more functionality.

**Comment by thebuddhaswords** [comment]
I've uploaded a page where the carriage returns were added manually. See the first paragraph of  https://thebuddhaswords.net/mn/mn8x.html   
(This is the Wisdom Pubs version) but was also inBW2 but I found and fixed it a few days ago. There are probably other pages but it's difficult to find them.  My previous example was a fabricated one to demonstrate the problem.

**Comment by thebuddhaswords** [comment]
Venerable Devamitta tells me that pallankena should be pallaṅkena which makes me wonder how many other ṅ's we're missing.

**Comment by cittadhammo** [comment]
Hi @bdhrs and @thebuddhaswords ,

I have started to look at that. I don't understand why the words are not cut out [in this place](https://thebuddhaswords.net/mn/mn8x.html):

![Screenshot 2024-02-22 at 09 43 54](https://github.com/thebuddhaswords/BW2/assets/82962905/06f5f467-7832-45f8-a53c-7cb4fbbc5265)

The span should be broken into two span, no ?

**Comment by cittadhammo** [comment]
This seems to be a fail of:
```js
var paliRex = /([aiueokgcjtdnpbmyrlvshāīūṭḍṅṇṁñḷ’­”]+)/i;
var splitRex = /([^  ,. – —:;?!“‘-]+)/;
function toLookupMarkup(startNode) {
  var parts, i, out = "", proxy, node;
  var it = new Iter(startNode, 'text');
  while (node = it.next()) if (node.nodeValue) {
    if (node.parentNode.nodeName == 'A')
      if (node.parentNode.parentNode.nodeName[0] != 'H')
        continue;
    out = "";
    parts = node.nodeValue.split(splitRex);
    for (i = 0; i < parts.length; i++) {
      if (i % 2 == 1) {// Word
        var word = parts[i]
        if (node.parentNode.nodeName != 'A')
          out += '<span class="lookup" onClick="return true">' + word + '</span>'
        else
          out += word
      } else { //Non-word
        out += parts[i];
      }
    }
    proxy = E('span');
    node.parentNode.replaceChild(proxy, node);
    proxy.outerHTML = out;
  }
}
```
Which generate the span element.

**Comment by cittadhammo** [comment]
Ok, I have added `\s` in the regex split and it works!

![Screenshot 2024-02-22 at 09 55 21](https://github.com/thebuddhaswords/BW2/assets/82962905/ca54c3bf-143e-48eb-9d83-db48bcb45858)

**Comment by cittadhammo** [comment]
for reference https://github.com/thebuddhaswords/BW2/commit/7a226f42ce72f4a69cac7518e4a000767a3b45a1

**Comment by cittadhammo** [comment]
Not sure, the pali search page is broken on my local copy. /home/palisearch.html

Is it related to this change?  I wait to see when the website is uploaded with the change. _The palisearch.html looks horrible ;-) with that big script on top..._

**Comment by thebuddhaswords** [comment]
This occurs when there is a manual line break within the Pali paragraph.
You wouldn't know they were there without looking at the HTML

I've fixed the ones I've found but it is difficult to find them all
therefore I've copied one page that I knew showed the problem (mn8x.html)
I'll delete it once you've got to see the issue in action.

The regex for them is \r\n  and programming the script to strip them off
would save me hunting any similar files down.


[image: image.png]

**Comment by thebuddhaswords** [comment]
The Pali Search page that is live on the web site looks and acts fine.

My local copy is fine and so is the one on Github. Maybe just grab a copy
of one of them?

Global search and replaces can cause unwanted side effects with the two
search pages but that isn't the cause this time??
