### ISSUE TITLE
dictionary pop-up text box misplacement

### ISSUE THREAD

**Issue by BBBalls** [thebuddhaswords/BW2#5]
A dictionary pop-up text box that has a large width, in reference to a word near the left side of the Pali column, it appears over the English text.

![Example of text box over English text](https://github.com/thebuddhaswords/BW2/assets/90289469/356abd3c-4139-4efb-9daf-72b9816afb61)

The size of the text box also does not seem to be purely deterministic. The size of the box can change, which also changes the behavior.

![Example of text box appearing with a smaller width, using the same word in the previous example](https://github.com/thebuddhaswords/BW2/assets/90289469/1df5fef3-e075-402f-92f6-760fb4810b86)

Text boxes with a shorter width and near the left side of the Pali column remain over the Pali text.

![Example of a short width box](https://github.com/thebuddhaswords/BW2/assets/90289469/4e56729c-431d-43cb-8744-988ef05ffef8)

Dictionary text boxes with larger widths for words favoring the right side of the Pali column remain over the Pali text.

![Example of larger width text box from a word near the right of the column](https://github.com/thebuddhaswords/BW2/assets/90289469/b5919e35-019a-47a7-9e47-5d3d5936bb34)

I noticed this in the bw2_20240219.zip version, and reproduced it in the git version. All the screenshots are from the git version as cloned 2024-02-21.

Arch Linux
Sway 1.8.1
Firefox 123.0

Edit:

I just utilized UnGoogled Chromium to see how the pop-up text box behaved. It behaves in a manner that conforms to an anticipated behavior.

**Comment by thebuddhaswords** [comment]
Hi and thanks for raising this issue. The updated site with the Pali Lookup is now live and I'm unable to reproduce the behaviour in your first screenshot. 

![image](https://github.com/thebuddhaswords/BW2/assets/96769121/151078ab-08bb-4884-ae20-d0fc168f1309)

A pop-up with the Pali dictionary entry should be impossible over the English. 🤯 The \js\pali-lookup-standalone script creates a table on the fly with English on the left and Pali on the right. On smaller screens Pali paragraphs get placed above the corresponding English paragraph but still within a table.

css then applies a  40 pixel left margin and the pop-up box is set to be a minimum of 20em and a maximum of 550 pixels. Any wider than 550 px messes up the display on small screens.

Here's the code for the css and I'd welcome any suggestions to improve it.  Where do you think the pop-up would be better placed? 

` .meaning {
 position:absolute;
 visibility:hidden;
 display:block;
 opacity: 0;
 bottom: 2.2em;
 margin-left: 40px;
 margin-right: auto;
 z-index: 1001;
 border: 1px solid darkorchid;
 background: #fff3d6;
 border-radius: 5px;
 font-size:16px;
 font-weight:normal;
 font-style:normal;
 text-decoration: none;
 text-align: left;
 padding: 0.1em 0.5em;
 margin-top:1em;
 min-width:20em;
 max-width:550px;
 height: auto;
 transition: 100ms;
}

**Comment by BBBalls** [comment]
The pop-up placement as it appears in Chromium is good, and behaves in a consistent manner. I don't think your css needs adjustment. I didn't think of looking at the site with Chromium, before making the issue. This seems to be an issue related to Firefox, and I submitted an issue https://github.com/webcompat/web-bugs/issues/133751 . I have been using the zip archive version in Firefox, and have notice few minor cosmetic issues, but they do not occur in Chromium either.

**Comment by thebuddhaswords** [comment]
Hi  ... thanks for letting me know and for closing the issue. I'm glad that
your finding the site useful and that you're taking advantage of the
ability to use the site offline.

All the best

Tom
