### ISSUE TITLE
TODO: the words in the popup must be able to be recursively looked up by clicking on them

### ISSUE THREAD

**Issue by cittadhammo** [thebuddhaswords/BW2#7]
With a pop up window it is quite tricky I believe as they will stack onto each other. Maybe having a side or bottom panel à la suttaCentral would make it easier. 

Solutions, 

- popup being closed and replaced by another, or a 
- botton bar is also cool. 
 
The old data tends to be horizontal in nature (i.e. suitable for top or bottom bar), compared to full dpd dictionary which tends to be longer vertically (i.e. suitable for a sidebar).

**Comment by cittadhammo** [comment]
> I DO like the idea of a hyperlink that takes the user deeper into the grammar part of the DPD but that is looking a bit (lot) like scope creep  :-)   Maybe you could give it some thought and how it would work on a mobile phone sixed screen? I any case, we are very close to having 100% of Pali words recognised across the whole site. That is a huge accomplishment and I'll let the people on Sutta Central's forum know about it once we're happy that the few little issues have been addressed.

**Comment by thebuddhaswords** [comment]
Dear Venerable,

The previous version of Pali lookup separated the Pali word and the 'iti
end quote and displayed the translation and added "end quote" but did it a
bit erratically. It would be my preference to copy that method.  I've
copied the code that was used into issue #4 and showed a few examples. I
hope that helps.

**Comment by thebuddhaswords** [comment]
This is not really required IMO. There are instances illustrated in issue #4 where there is an issue with separating the Pali word from it's following end quote.  As far as I know the handling of the 'ti end quotes are the only situations where this is an issue and Issue #4 covers that. Closing this issue.
