### ISSUE TITLE
Locate and fix words with n instead of ṅ

### ISSUE THREAD

**Issue by thebuddhaswords** [thebuddhaswords/BW2#8]
Venerable Devamitta alerted me to the misspelling of pallankena (should be pallaṅkena). Those occurrences have been fixed and the changes uploaded to the live website however I'd like to locate any other words where "ṅ" has been replaced with an "n" but I've got no idea how to locate them. Another approach might be is to programmatically try to match the word by substituting the n with an ṅ

**Comment by bdhrs** [comment]
Here's a list of words in Sutta Central texts which contain the letter "ṅ". [words_with_ṅ_in_sc_texts.txt](https://github.com/thebuddhaswords/BW2/files/14381086/words_with_._in_sc_texts.txt)

I have no easy way to exatrct the words from TBW and compare them. Perhaps there's a pattern to the problem, like "ṅk" > "nk", that would help to solve your problem faster.

**Comment by thebuddhaswords** [comment]
Working through 2,400+ words with an ṅ. Thanks for the list!   nk to ṅk doesn't work as it also finds "bank", "ankle" etc  :-(   On the plus side "saṅgha" gets lots of words fixed in one hit. I'll do a search and replace for word forms that are common in Pali but not English to reduce the number yet to be checked. e.g. "aṅgaṁ" etc.

**Comment by thebuddhaswords** [comment]
Pavel (https://github.com/o28o) has sorted this out with some clever coding and a lot of patience. He saved me a week or more of work. Thanks Pavel!
